/**
 * TANTRAMOUR 2027 — Données AGENDA
 * Généré via Creation_Planning.html
 */
var AGENDA = [
  {id:"A_4797",jour:"Jour 1",date:"Samedi 28 août",heure:"23:15 - 26:15",type:"LOVE TEMPLE",atelier:"Love Temple 1",lieu:"CHENREZIG",fac1:"Jivan Muti (Clément Victor)",fac1Id:"203021",fac2:"",fac2Id:"",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3974",jour:"Jour 1",date:"Samedi 28 août",heure:"10:15 - 11:15",type:"ATELIERS TANTRA",atelier:"TANTRA 1",lieu:"SHAKTI",fac1:"Audrey Barthélémy",fac1Id:"530949",fac2:"",fac2Id:"",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_8383",jour:"Jour 2",date:"Dimanche 29 août",heure:"09:00 - 10:30",type:"MEDITATION / YOGA",atelier:"Meditation du matin",lieu:"SHIVA",fac1:"Sevda Duroy",fac1Id:"895935",fac2:"",fac2Id:"",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_1936",jour:"Jour 2",date:"Dimanche 29 août",heure:"14:15 - 16:15",type:"DJ Set",atelier:"Dj Set",lieu:"CHENREZIG",fac1:"DJ Surprise",fac1Id:"553197",fac2:"",fac2Id:"",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5094",jour:"Jour 2",date:"Dimanche 29 août",heure:"13:30 - 15:00",type:"CONFERENCE",atelier:"Conférence 1",lieu:"SHAKTI",fac1:"Laurent Lacoste",fac1Id:"728800",fac2:"Laurence Heitzmann",fac2Id:"738974",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_3781",jour:"Jour 1",date:"Samedi 28 août",heure:"17:45 - 20:15",type:"CEREMONIE & CONCERT",atelier:"Céremonie 1",lieu:"SHIVA",fac1:"Amana",fac1Id:"845215",fac2:"",fac2Id:"",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""},
  {id:"A_5692",jour:"Jour 1",date:"Samedi 28 août",heure:"14:15 - 16:15",type:"TANTRA CAFE",atelier:"Tantra Café",lieu:"CHENREZIG",fac1:"Sandrine Bettinelli",fac1Id:"621869",fac2:"Jivan Muti (Clément Victor)",fac2Id:"203021",fac3:"",fac3Id:"",fac4:"",fac4Id:"",traduction:"",helper1:"",helper2:"",helper3:"",helper4:"",angel:"",note:"",piment:1,colibri:false,logisticId:"",meetingRoles:""}
];
