/**
 * TANTRAMOUR 2026 — Référentiel : Équipements
 * Chaque entrée : { id, value, type, categorie, stock, description, remarque }
 *   value       : nom de l'équipement
 *   type        : "Hameau" | "Tantramour" | "Animateur" | "Autre" (fournisseur)
 *   categorie   : nom de la catégorie — géré via ref_equip_cat.js (REF_EQUIP_CAT)
 *   stock       : nombre (0-1000) ou "N/A"
 *   description : texte libre
 *   remarque    : texte libre
 */
var REF_EQUIPEMENTS = [
  { type: "Hameau", categorie: "Matériel de Pratique", id: 219876, value: "Tapis de Yoga", stock: 141, description: "Tapis de Yoga", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: 518961, value: "Brique de yoga", stock: 34, description: "Brique de yoga", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: 675850, value: "Matelas", stock: 169, description: "Matelas", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: 433736, value: "Micro Casque", stock: 0, description: "Micro Casque", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 186907, value: "Chaise", stock: 246, description: "Chaise", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 592798, value: "Table", stock: 0, description: "Table", remarque: "" },
  { type: "Hameau", categorie: "Fournitures", id: 330281, value: "Paperboard", stock: 12, description: "Paperboard", remarque: "" },
  { type: "Hameau", categorie: "Décoration & Rituel", id: 665097, value: "Miroir", stock: 1, description: "Miroir", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 944521, value: "Saladier", stock: 0, description: "Saladier", remarque: "" },
  { type: "Hameau", categorie: "Consommables Hygiène", id: 396589, value: "Serviette de toilette", stock: 0, description: "Serviette de toilette", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 481801, value: "Bassine", stock: 0, description: "Bassine", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 351778, value: "Casserole", stock: 0, description: "Casserole", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 576250, value: "Louche", stock: 0, description: "Louche", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 337909, value: "Spot lumineux chromé", stock: "N/A", description: "Spot lumineux", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 147544, value: "Lingette humide", stock: 0, description: "Lingette humide", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 704501, value: "Boite mouchoirs", stock: 0, description: "Boite mouchoirs", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 829406, value: "Talc", stock: 0, description: "Talc", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 842452, value: "Huile de coco", stock: 0, description: "Huile de coco", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 784361, value: "Petite coupelle (huile)", stock: 0, description: "Petite coupelle (huile)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 601447, value: "Bougie chauffe plat (vraie)", stock: 0, description: "Bougie chauffe plat (vraie)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 822678, value: "Bougie cierge (vraie)", stock: 0, description: "Bougie cierge (vraie)", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 317620, value: "Briquet", stock: 0, description: "Briquet", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 630274, value: "Bougie chauffe plat (LED)", stock: 0, description: "Bougie chauffe plat (LED)", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 266030, value: "Bougie cierge (LED)", stock: 0, description: "Bougie cierge (LED)", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: 247154, value: "Ramette de papier", stock: 0, description: "Ramette de papier", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: 885033, value: "Crayon", stock: 0, description: "Crayon", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 551170, value: "Palo Santo", stock: 0, description: "Palo Santo", remarque: "" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: 278110, value: "Masque pour les yeux", stock: 0, description: "Masque pour les yeux", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: 298934, value: "Micro Sans Fil", stock: 0, description: "Micro Sans Fil", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: 184081, value: "Micro Câble - Tonor", stock: 1, description: "Micro Câble - Tonor", remarque: "" },
  { type: "Animateur", categorie: "Décoration & Rituel", id: 742107, value: "Tenture", stock: 0, description: "Tenture", remarque: "" },
  { type: "Animateur", categorie: "Matériel de Pratique", id: 968228, value: "Tambour", stock: 0, description: "Tambour", remarque: "" },
  { type: "Animateur", categorie: "Décoration & Rituel", id: 856259, value: "Clochette", stock: 0, description: "Clochette", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 718045, value: "Rose rouge", stock: 0, description: "Rose rouge", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 326333, value: "Rose blanche", stock: 0, description: "Rose blanche", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 415983, value: "Bouquet de fleurs (variées)", stock: 0, description: "Bouquet de fleurs (variées)", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 709815, value: "Bouquet de roses", stock: 0, description: "Bouquet de roses", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Technique & Son", id: 613023, value: "Pied Micro (FELIX)", stock: 0, description: "Pied Micro (FELIX)", remarque: "Demander à Felix" },
  { type: "Hameau", categorie: "Technique & Son", id: 939332, value: "Connecteur iPhone 16", stock: "N/A", description: "Connecteur iPhone 16", remarque: "pour playlist" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: 724821, value: "Glaçons (Kg)", stock: 0, description: "Glaçons (Kg)", remarque: "A ACHETER" },
  { type: "Tantramour", categorie: "Matériel de Pratique", id: 627615, value: "Piscine gonflable", stock: 0, description: "Piscine gonflable", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 767424, value: "Table mange debout", stock: 3, description: "Table mange debout", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: 484708, value: "Récepteur Bluetooth", stock: 4, description: "Récepteur Bluetooth", remarque: "Récepteur Bluetooth" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 992370, value: "Fauteuil blanc", stock: 8, description: "Fauteuil blanc", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 808714, value: "Petite table", stock: 15, description: "Petite table", remarque: "Petite table noire carrée" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 971171, value: "Table de massage", stock: 29, description: "Table de massage", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: 595207, value: "Zafu festivalier", stock: 32, description: "Zafu festivalier", remarque: "" },
  { type: "Hameau", categorie: "Aménagement & Equipements", id: 702323, value: "Grande table pliante #1 (122 cm)", stock: 58, description: "Grande table pliante #1 (122 cm)", remarque: "Table grise pliante (122cm/60cm/74cm hauteur)" },
  { type: "Hameau", categorie: "Technique & Son", id: 366202, value: "Table de mixage", stock: 0, description: "Table de mixage", remarque: "" },
  { type: "Hameau", categorie: "Technique & Son", id: 955940, value: "Sono", stock: 0, description: "Sono", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 556895, value: "Assiette grande", stock: 0, description: "Assiette grande", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 230451, value: "Assiette petite", stock: 0, description: "Assiette petite", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 542300, value: "Sopalin", stock: 0, description: "Sopalin", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: 846833, value: "Bobseat", stock: 10, description: "Bobseat", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 933454, value: "Bougie chandelle (vraie)", stock: 0, description: "Bougie chandelle (vraie)", remarque: "" },
  { type: "Animateur", categorie: "Matériel de Pratique", id: 269775, value: "Corde Shibari", stock: 0, description: "Corde Shibari", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: 260305, value: "Coussin", stock: 360, description: "Coussin", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 259878, value: "Cuillère à café", stock: 0, description: "Cuillère à café", remarque: "" },
  { type: "Hameau", categorie: "Cuisine", id: 586359, value: "Cuillière à soupe", stock: 0, description: "Cuillière à soupe", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 295303, value: "Encens", stock: 0, description: "Encens", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 772873, value: "Gel hydroalcoolique", stock: 0, description: "Gel hydroalcoolique", remarque: "" },
  { type: "Tantramour", categorie: "Cuisine", id: 484583, value: "Gobelet carton", stock: 200, description: "Gobelet carton", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: 107517, value: "Câble Branchement Guitare", stock: "N/A", description: "Câble Branchement Guitare", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: 826189, value: "Connecteur pour pédalier", stock: "N/A", description: "Connecteur pour pédalier", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: 188106, value: "Connectique iPhone", stock: "N/A", description: "Connectique iPhone", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: 568640, value: "Mini-jack pour iMac", stock: "N/A", description: "Mini-jack pour iMac", remarque: "" },
  { type: "Autre", categorie: "Technique & Son", id: 728884, value: "Alimentation électrique 220v (3)", stock: "N/A", description: "Alimentation électrique 220v (3)", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: 511429, value: "Entrée XLR ou Jack 6,35mm", stock: "N/A", description: "Entrée XLR ou Jack 6,35mm", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 970571, value: "Huile de sésame", stock: 0, description: "Huile de sésame", remarque: "" },
  { type: "Tantramour", categorie: "Consommables Hygiène", id: 286497, value: "Sopalin", stock: 0, description: "Sopalin", remarque: "" },
  { type: "A définir", categorie: "Technique & Son", id: 979765, value: "Stand Guitare", stock: 0, description: "Stand Guitare", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 746086, value: "Support bougie chandelle", stock: 0, description: "Support bougie chandelle", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 363482, value: "Tapis de sol décoratif", stock: 0, description: "Tapis de sol décoratif", remarque: "" },
  { type: "Tantramour", categorie: "Fournitures", id: 970839, value: "Bouteilles d'eau", stock: 0, description: "Bouteilles d'eau", remarque: "" },
  { type: "Hameau", categorie: "Matériel de Pratique", id: 315721, value: "Zafu animateur", stock: 32, description: "Zafu animateur", remarque: "" },
  { type: "Tantramour", categorie: "Décoration & Rituel", id: 842912, value: "Petites fleurs séchées", stock: "N/A", description: "pour autel Shiva", remarque: "" },
  { type: "Hameau", categorie: "Décoration & Rituel", id: 177693, value: "Vase", stock: "N/A", description: "", remarque: "" },
  { type: "Tantramour", categorie: "Eclairage", id: 530849, value: "Spot lumineux noir", stock: "N/A", description: "", remarque: "" },
];
