-- ============================================================
-- TANTRAMOUR 2027 — Seed : ref_display_reports
-- Source : ref_display_reports.js (37 entrées)
-- À exécuter dans Supabase SQL Editor
-- Upsert idempotent : safe à relancer
-- ============================================================

INSERT INTO public.ref_display_reports
  (id, title, title_key, "desc", desc_key, icon, url, section,
   show_in_dreamteam, active, card_style, icon_style, title_style, desc_style, arrow_style, is_protected, "order")
VALUES
  ('rep_programme',               'Programme Festival',                       'card_programme_title',            'Ateliers publics par jour — descriptions & détails',                                              'card_programme_desc',             '🎪', 'Rapport_Programme.html',                    'DreamTeam',              true,  true,  'background:#3b82d4;border-color:#3b82d4;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 1),
  ('rep_mon_planning_v2',         'Mon Planning',                             'card_mon_planning_v2_title',      'Vue par ressource — détails ateliers, logistique, popup FR/EN',                                   'card_mon_planning_v2_desc',       '📋', 'Rapport_Mon_Planning_V2.html',              'DreamTeam',              true,  true,  'background:#fef9c3;border-color:#fde68a;color:#111;',         'background:rgba(255,255,255,.45);border-color:rgba(17,17,17,.12);', 'color:#111;',    'color:rgba(17,17,17,.78);',   'color:rgba(17,17,17,.7);',    false, 2),
  ('rep_mon_agenda_simplifie',    'Mon Agenda Simplifié',                     'card_mon_agenda_simplifie_title', 'Agenda visuel filtré par nom — couleur selon votre rôle dans chaque atelier',                      'card_mon_agenda_simplifie_desc',  '🗓️', 'Rapport_Mon_Agenda_Simplifie.html',         'DreamTeam',              true,  true,  'background:#f0fdf4;border-color:#86efac;color:#111;',         'background:rgba(255,255,255,.6);border-color:#86efac;',             'color:#166534;', 'color:#166534cc;',            'color:#16a34a;',             false, 3),
  ('rep_agenda_simplifie_salle',  'Agenda Simplifié par Salle',               'card_agenda_simplifie_salle_title','Vue calendrier par salle — tous les ateliers d''une salle positionnés à l''heure',              'card_agenda_simplifie_salle_desc','🏛️', 'Rapport_Agenda_Simplifie_par_Salle.html',   'DreamTeam',              false, true,  'background:#fce7f3;border-color:#f9a8d4;color:#9d174d;',      'background:rgba(255,255,255,.6);border-color:#f9a8d4;',             'color:#9d174d;', 'color:#be185d;',              'color:#f472b6;',             false, 4),
  ('rep_agenda_simplifie',        'Agenda Simplifié',                         'card_agenda_simplifie_title',     'Vue calendrier par jour & lieu — tous les ateliers positionnés à l''heure',                      'card_agenda_simplifie_desc',      '🗓️', 'Rapport_Agenda_Simplifie.html',             'DreamTeam',              false, true,  'background:#fce7f3;border-color:#f9a8d4;color:#9d174d;',      'background:rgba(255,255,255,.6);border-color:#f9a8d4;',             'color:#9d174d;', 'color:#be185d;',              'color:#f472b6;',             false, 5),
  ('rep_angels_shifts',           'Planning Angel',                           'card_angel_title',                'Vue du planning des Angels ainsi que leur contact',                                               'card_angel_desc',                 '👼', 'Rapport_Angels_Shifts.html',                'DreamTeam',              true,  true,  'border-color:#f9a8d4;',                                       '',                                                                  '',               '',                            '',                           false, 6),
  ('rep_traducteurs',             'Planning Traducteurs',                     'card_traducteurs_title',          'Vue par traducteur — shifts regroupés, filtres Jour/Traducteur',                                  'card_traducteurs_desc',           '🌐', 'Rapport_Traducteurs.html',                  'DreamTeam',              true,  true,  '',                                                            '',                                                                  '',               '',                            '',                           false, 7),
  ('rep_colibri',                 'Planning Colibri',                         'card_colibri_title',              'Ateliers avec animateur ayant le rôle Shift Colibri',                                             'card_colibri_desc',               '🐦', 'Rapport_Colibri.html',                      'DreamTeam',              true,  true,  'border-color:#c4b5fd;',                                       '',                                                                  '',               '',                            '',                           false, 8),
  ('rep_news',                    'NEWS',                                     'card_news_title',                 'Publier & gérer les messages importants DreamTeam et Festivaliers',                               'card_news_desc',                  '📢', 'Rapport_News.html',                         'Admin',                  false, true,  'background:#7c3aed;border-color:#7c3aed;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 1),
  ('rep_editer_accueil',          'Éditer Accueil (index)',                   'card_editer_index_title',         'Modifier les textes de la page d''accueil (dates, titre, site web)',                              'card_editer_index_desc',          '✏️', 'Rapport_Editer_Accueil.html',               'Admin',                  false, true,  'background:#eff6ff;border-color:#bfdbfe;color:#1e40af;',      'background:rgba(255,255,255,.6);border-color:#bfdbfe;',             'color:#1e40af;', 'color:#1e3a8a;',              'color:#3b82d4;',             false, 1),
  ('rep_master_data',             'Master Data',                              'nav_masterdata',                  'Gestion des référentiels de données (Lieux, Équipements, Consignes, etc.)',                      'card_masterdata_desc',            '🗂',  'MasterData.html',                           'Admin',                  false, true,  'border-color:#94a3b8;',                                       '',                                                                  '',               '',                            '',                           false, 2),
  ('rep_gerer_ressources',        'Gérer les Ressources',                     'card_ressources_title',           'Animateurs, Helpers, Traducteurs, Angels — référentiel unifié éditable',                         'card_ressources_desc',            '👥', 'Rapport_Gerer_Ressources.html',             'Admin',                  false, true,  'border-color:#86efac;',                                       '',                                                                  '',               '',                            '',                           false, 3),
  ('rep_remplacement_ressource',  'Remplacement de Ressource',                'card_remplacement_title',         'Personne indisponible — proposition automatique de remplaçants sans conflit',                    'card_remplacement_desc',          '🔄', 'Rapport_Remplacement_Ressource.html',       'Admin',                  false, false, 'border-color:#fca5a5;',                                       '',                                                                  '',               '',                            '',                           true,  9),
  ('rep_gestion_affichage',       'Gestion Affichage',                        'card_gestion_affichage_title',    'Organiser, activer ou déplacer les rapports dans les sections',                                   'card_gestion_affichage_desc',     '🎛️', 'Rapport_Gestion_Affichage.html',            'Admin',                  false, true,  'background:#1e3a8a;border-color:#1e3a8a;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 5),
  ('rep_admin',                   'Admin',                                    'nav_admin',                       'Paramètres globaux et administration de l''application',                                         'card_admin_desc',                 '⚙️', 'Admin.html',                                'Admin',                  false, false, 'border-color:#94a3b8;',                                       '',                                                                  '',               '',                            '',                           true,  6),
  ('rep_manuel',                  'Manuel utilisateur',                       'nav_manuel',                      'Guide d''utilisation complet de la plateforme',                                                  'card_manuel_desc',                '📖', 'user-manual.html',                          'Admin',                  false, true,  'border-color:#94a3b8;',                                       '',                                                                  '',               '',                            '',                           false, 7),
  ('rep_regles',                  'Règles & Documentation',                   'nav_regles',                      'Spécifications métier et règles de gestion du festival',                                         'card_regles_desc',                '📐', 'Rapport_Regles.html',                       'Admin',                  false, true,  'border-color:#94a3b8;',                                       '',                                                                  '',               '',                            '',                           false, 8),
  ('rep_transform_upload',        'Convertir Fiche Atelier',                  'card_transform_upload_title',     'Convertir les fiches animateurs en fichier logistique consolidé (.xlsx)',                        'card_transform_upload_desc',      '🔄', 'TRANSFORM_UPLOAD.html',                     'Gestion planning',       false, true,  'background:#0f766e;border-color:#0f766e;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 1),
  ('rep_infos_ateliers',          'Upload des fiches Ateliers',               'card_ria_title',                  'Consignes, besoins logistiques et infos pour helpers et intervenants',                           'card_ria_desc',                   'ℹ️', 'Rapport_Informations_Ateliers.html',        'Gestion planning',       false, true,  'background:#16a34a;border-color:#16a34a;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 2),
  ('rep_editer_atelier',          'Éditer un atelier',                        'card_editer_title',               'Sélectionnez un atelier et modifiez ses champs en direct',                                       'card_editer_desc',                '✏️', 'Rapport_Editer_Atelier.html',               'Gestion planning',       false, true,  'background:#4b5563;border-color:#374151;color:#fff;',         'background:rgba(255,255,255,.15);border-color:rgba(255,255,255,.25);','color:#fff;',   'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.6);', false, 3),
  ('rep_saisie_ateliers',         'Validation avec Animateurs (Info Ateliers)','card_saisie_ateliers_title',     'Validation avec Animateurs (Info Ateliers)',                                                      'card_saisie_ateliers_desc',       '📋', 'Rapport_Saisie_Ateliers.html',              'Gestion planning',       false, true,  'background:#ca8a04;border-color:#ca8a04;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 4),
  ('rep_agenda_jour',             'Planning par Jour',                        'card_agenda_jour_title',          'Tous les ateliers — filtres jour, lieu, rôle',                                                   'card_agenda_jour_desc',           '📅', 'Rapport_Agenda_par_Jour.html',              'Gestion planning',       false, true,  '',                                                            '',                                                                  '',               '',                            '',                           false, 5),
  ('rep_trad_affectation',        'Affectation Traducteur',                   'card_trad_affect_title',          'Ateliers anglophones sans traducteur — détection TBC et affectation guidée',                    'card_trad_affect_desc',           '🌐✅','Rapport_Traducteur_Affectation.html',       'Gestion planning',       false, false, 'border-color:#c4b5fd;',                                       '',                                                                  '',               '',                            '',                           true,  6),
  ('rep_ateliers_proposes',       'Ateliers Proposés',                        'card_ateliers_proposes_title',    'Gérer les ateliers proposés — créer, valider (NEW / APPROVED / REJECTED)',                      'card_ateliers_proposes_desc',     '🌱', 'Rapport_Ateliers_Proposes.html',            'Gestion planning',       false, true,  'background:#166534;border-color:#166534;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 7),
  ('rep_creation_planning',       'Création du Planning',                     'card_creation_planning_title',    'Module visuel de conception du planning — template Outlook & drag and drop des ateliers retenus','card_creation_planning_desc',     '🗓️', 'Creation_Planning.html',                    'Gestion planning',       false, true,  'background:#2563eb;border-color:#2563eb;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 8),
  ('rep_charge_travail',          'Charge de travail (Workload)',              'card_charge_title',               'Helpers & Angels — nombre d''ateliers, durée, harmonisation',                                   'card_charge_desc',                '⚖️', 'Rapport_Charge_Travail.html',               'Contrôle & Vérification', false, true,  'background:#7c3aed;border-color:#6d28d9;color:#fff;',         'background:rgba(255,255,255,.15);border-color:rgba(255,255,255,.25);','color:#fff;',   'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.6);', false, 1),
  ('rep_conflits',                'Conflits de planning',                     'card_conflits_title',             'Personnes assignées à plusieurs rôles simultanément',                                            'card_conflits_desc',              '⚠️', 'Rapport_Conflits.html',                     'Contrôle & Vérification', false, true,  '',                                                            '',                                                                  '',               '',                            '',                           false, 2),
  ('rep_problemes',               'Problèmes de planning',                    'card_problemes_title',            'Ateliers anglophones sans traducteur · Ressources insuffisantes — correction inline',             'card_problemes_desc',             '🚨', 'Rapport_Problemes.html',                    'Contrôle & Vérification', false, true,  'border-color:#fca5a5;',                                       '',                                                                  '',               '',                            '',                           false, 3),
  ('rep_desc_manquantes',         'Descriptions manquantes',                  'card_desc_manq_title',            'Ateliers sans description FR ou EN — suivi et accès direct à l''éditeur',                       'card_desc_manq_desc',             '📋', 'Rapport_Descriptions_Manquantes.html',      'Contrôle & Vérification', false, false, 'border-color:#fcd34d;',                                       '',                                                                  '',               '',                            '',                           true,  4),
  ('rep_log_manquante',           'Logistique manquante',                     'card_log_manq_title',             'Ateliers sans info logistique ou non validés par les animateurs',                                'card_log_manq_desc',              '📦', 'Rapport_Logistique_Manquante.html',         'Contrôle & Vérification', false, false, 'border-color:#fca5a5;',                                       '',                                                                  '',               '',                            '',                           true,  5),
  ('rep_besoins_equipements',     'Besoins Équipements',                      'card_besoins_eq_title',           'Tableau de bord des équipements demandés par atelier — filtres, tri, export',                   'card_besoins_eq_desc',            '🔩', 'Rapport_Besoins_Equipements.html',          'Logistique',             false, false, 'background:#0f766e;border-color:#0f766e;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 3),
  ('rep_gestion_equipements_ateliers','Gestion des équipements par Atelier (Export/Import)','card_gestion_eq_ateliers_title','Export et import des équipements par atelier — validation ligne par ligne',            'card_gestion_eq_ateliers_desc',   '📦', 'Rapport_Gestion_Equipements_Ateliers.html', 'Logistique',             false, true,  'background:#0f766e;border-color:#0f766e;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 4),
  ('rep_stock_equipements_lieux', 'Stock & Équipements par Lieu',             'card_stock_eq_lieux_title',       'Gestion des stocks face aux pics demandés par salle & alertes de dépassement',                  'card_stock_eq_lieux_desc',        '🏛️', 'Rapport_Stock_Equipements_Lieux.html',      'Logistique',             false, true,  'background:#0d9488;border-color:#0d9488;color:#fff;',         'background:rgba(255,255,255,.2);border-color:rgba(255,255,255,.3);', 'color:#fff;',    'color:rgba(255,255,255,.8);', 'color:rgba(255,255,255,.7);', false, 5),
  ('rep_log_speciale',            'Logistique Spéciale',                      'card_log_spec_title',             'Tous les besoins logistiques spéciaux renseignés par les animateurs',                            'card_log_spec_desc',              '⭐', 'Rapport_Logistique_Speciale.html',          'Logistique',             false, false, 'border-color:#c4b5fd;',                                       '',                                                                  '',               '',                            '',                           true,  4)
ON CONFLICT (id) DO UPDATE SET
  title             = EXCLUDED.title,
  title_key         = EXCLUDED.title_key,
  "desc"            = EXCLUDED."desc",
  desc_key          = EXCLUDED.desc_key,
  icon              = EXCLUDED.icon,
  url               = EXCLUDED.url,
  section           = EXCLUDED.section,
  show_in_dreamteam = EXCLUDED.show_in_dreamteam,
  active            = EXCLUDED.active,
  card_style        = EXCLUDED.card_style,
  icon_style        = EXCLUDED.icon_style,
  title_style       = EXCLUDED.title_style,
  desc_style        = EXCLUDED.desc_style,
  arrow_style       = EXCLUDED.arrow_style,
  is_protected      = EXCLUDED.is_protected,
  "order"           = EXCLUDED."order",
  updated_at        = now();
